artifacts_root: artifacts

collect_data:
  root_dir: artifacts/data_collection
  source_PATH: /home/cdot/PycharmProjects/real_and_fake_face.zip
  local_data_file: artifacts/data_collection/data.zip
  unzip_dir: artifacts/data_collection
